- hosts: localhost
  become: yes
  tasks:
    - name: Check kernel version.
      fail: msg="Kernel {{ ansible_kernel }} is not supported."
      when: "ansible_kernel | version_compare('3.10', '<')"
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # One day
    - name: apt install packages
      apt: 
        name: "{{ item }}"
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker’s official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Check docker gpg key.
      shell: apt-key fingerprint 0EBFCD88 | grep 0EBFCD88
      ignore_errors: True

    - name: define lsb_release -cs
      shell: lsb_release -cs
      ignore_errors: True
      register: lsb_release

    - name: set up the stable repository
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

    - name: Install docker-ce.
      apt: name=docker-ce state=present update_cache=yes
      notify:
        - restart docker