- hosts: localhost
  # remote_user: server
  # gather_facts: no
  become: yes

  tasks:
    - name: inventory_hostname is
      debug: var=inventory_hostname
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # One day

    # CUDA, cuDNN, NCCL, TensorRT
    - name: Add NVIDIA key
      apt_key:
        url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    - name: Install NVIDIA network deb from the network
      apt:
        deb: "{{ item }}"
      with_items:
        - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb
        - https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
        - https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvinfer-runtime-trt-repo-ubuntu1804-5.0.2-ga-cuda10.0_1-1_amd64.deb
    - name: Install CUDA, cuDNN, NCCL, TensorRT based on network deb's config
      apt:
        update_cache: yes
        force: yes
        name: "{{ item }}"
      with_items:
          - cuda-10-0
          - libcudnn7=7.5.0.56-1+cuda10.0
          - libcudnn7-dev=7.5.0.56-1+cuda10.0
          - libnccl2=2.4.2-1+cuda10.0
          - libnccl-dev=2.4.2-1+cuda10.0
          - libnvinfer5=5.0.2-1+cuda10.0
          - libnvinfer-dev=5.0.2-1+cuda10.0
    - name: Prevent cuda related packages from upgrading
      command: aptitude hold "{{ item }}"
      with_items:
        - cuda-repo-ubuntu1804
        - nvidia-machine-learning-repo-ubuntu1804
        - nvinfer-runtime-trt-repo-ubuntu1804-5.0.2-ga-cuda10.0
        - cuda-10-0
        - libcudnn7
        - libcudnn7-dev
        - libnccl2
        - libnccl-dev
        - libnvinfer5
        - libnvinfer-dev